apiVersion: gatemin.io/v1alpha1
kind: IngressGate
metadata:
  name: {{ template "mailhog.fullname" . }}
spec:
  host: mailhog-ot-it4ot-dev.apps.ocp-prd.alliander.com
  auth:
    type: NONE
  services:
    - backend:
        serviceName: {{ template "mailhog.fullname" . }}
        servicePort: {{ .Values.service.port }}
      path: /
