apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World 000"
  description_no_quotes: {{ .Chart.Description }}
  filename: {{ .Files.Get "demo.txt" }}
  filenameb64: {{ .Files.Get "demo.txt" | b64enc }}
  drink: {{ .Values.favoriteDrink }}
