apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World 000"
  description: {{ .Chart.Description | quote }} #  the description in Chart.yaml
  description_no_quotes: {{ .Chart.Description }} #  the description in Chart.yaml